apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-otel
  namespace: opentelemetry-operator-system
spec:
  mode: sidecar
  config:
    receivers:
      jaeger:
        protocols:
          thrift_compact: {}
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    exporters:
      logging:
        loglevel: debug

      otlp/jaeger:
        endpoint: "simple-prod-collector.observability.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [jaeger, otlp]
          processors: [batch]
          exporters: [logging, otlp/jaeger]
