kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-fmm
  namespace: api
  labels:
    app: api-fmm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-fmm
  template:
    metadata:
      labels:
        app: api-fmm
    spec:
      containers:
        - name: api-fmm
          image: fernandomarca/api-fmm:latest
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - name: http
              containerPort: 3333
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3333"
            - name: DATABASE_URL
              value: postgres://postgres:apifmm261186@postgres-headless.db.svc.cluster.local/postgres
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
