apiVersion: v1
kind: Service
metadata:
  name: api-fmm
  namespace: api
  labels:
    app: api-fmm
spec:
  type: ClusterIP
  selector:
    app: api-fmm
  ports:
    - name: http
      port: 3333
      targetPort: 3333
